### ISSUE TITLE
.env does not exist on the remote

### ISSUE THREAD

**Issue by ltarasiewicz** [roots/bedrock-capistrano#2]
Hello, 

I might be still confused about the configuration, but when I execute 
`bundle exec cap <stage> deploy:check`, I get the following error

> ERRORlinked file /srv/www/cpkg/shared/.env does not exist on (my_remote_host)

Then the 5th point of your installation instruction says:

> > Add your .env file to shared/ in your deploy_to path on the remote server for all the stages you use (ex: /srv/www/example.com/shared/.env)

Does that mean that I first have to manually copy `.env` to a remote server where I want to deploy to?

I will be grateful for a word of explanation.

**Comment by swalkinshaw** [comment]
Yes, that's correct. Since it doesn't live in your Git repo you need to manually get it onto the server somehow.

Our https://github.com/roots/bedrock-ansible project takes care of this automatically, but otherwise it's up to you.
