### ISSUE TITLE
/usr/bin/env: No such file or directory

### ISSUE THREAD

**Issue by koraysels** [roots/bedrock-capistrano#4]
I am getting deploy errors..

```
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host 87.***.1**.2**: mkdir exit status: 127
mkdir stdout: Nothing written
mkdir stderr: -: /usr/bin/env: No such file or directory
```

I have no idea why it uses `/usr/bin/env`. On My server it is`/bin/env` ....
No idea how to change it :(

**Comment by swalkinshaw** [comment]
You need to modify your [command map](https://github.com/capistrano/sshkit#the-command-map) for `env`.

``` ruby
SSHKit.config.command_map[:env] = '/bin/env'
```

**Comment by koraysels** [comment]
where do I put this ? in deploy.rb ? because it doesn't work there ... ?

**Comment by swalkinshaw** [comment]
Looks like Capistrano doesn't let you change `/usr/bin/env`. You can just symlink `/bin/env` to `/usr/bin/env`.

**Comment by koraysels** [comment]
bummers :( i think I don't have permissions to do this 

```
$ ln -s /bin/env /usr/bin/env
ln: creating symbolic link `/usr/bin/env': No such file or directory
```

`$ /bin/env` is there and working
