### ISSUE TITLE
Configuration steps problem

### ISSUE THREAD

**Issue by Paolocargnin** [roots/bedrock-capistrano#5]
First of all, sorry for my english.

As describe in this issue -> https://github.com/roots/bedrock-capistrano/issues/2

I had the same problem because the readme said to before run the _bundle exec cap <stage> deploy:check_ and after add the .env on the server.

Making the opposite (so creating the .env file before and then execute the _bundle exec cap <stage> deploy:check_ ) the things go Okay.

**Maybe it's better to change the readme file?**

Anyway, after that, executing the last command ( _bundle exec cap <stage> deploy_)

i got this error: 
**fatal: destination path _'/var/www/vhosts/fondazionemorgani.boom.ink/repo'_ already exists and is not an empty directory.**

( obvsiouly, the directory is empty when I start the process, the only thing that it has is the shared/.env file, and the _releases_ directory (and it is empty) )

Googling online, i tried to delete the repo folder after this and re-run _bundle exec cap <stage> deploy_ but then the message is: 
**failed to create symbolic link '#{deploy_path}/releases/20160106135547/.env': File exists**

Again, obviously, the .env file isn't in my repo.

From now on, I can't continue because i really doesn't know what to do.

I really can't figure out what I'm forgetting... 5 months ago I already installed the capistrano bedrock deploy and everything went ok... 

Can you guys help me?

**Comment by Paolocargnin** [comment]
Ok, it simply was an error on my **staging.rb** file

I've set the role app and the server in two different method, one with the domain name of the server, and one with the IP.

Sorry. 

[Walk away in shame]

**Comment by swalkinshaw** [comment]
No problem, thanks for sharing the solution :)
